name: deplpyign the go file 

on: 
  push: 
    branches: 
      - main 
    paths-ignore: 
      - 'READEME.md'
jobs: 
  build: 
    runs-on: ubuntu-latest 

    steps: 
      - name: checkout the repository 
        uses: actions/checkout@v4
      - name: setup the go 1.22 
        uses: actions/setup-go@v2
        with: 
          go-version: 1.22 
      - name: displaying the all files and folders in repository 
        run: ls 
     
      - name: displaying the all testcases along with the testcases 
        run: ls 
      - name: setting up the docker 
        uses: docker/setup-buildx-action@v1

      - name: login to the docekr 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  test: 
    needs: build 
    steps: 
    - name: checkout the repository 
      uses: actions/checkout@v4 
    - name: checkout the test cases 
      run: 
        git clone https://github.com/mohantest14242/go_testing.git
    - name: displayin the all files 
      run: ls
  

      