name: deplpyign the go file 

on: 
  push: 
    branches: 
      - main 
    paths-ignore: 
      - 'READEME.md'
jobs: 
  build: 
    runs-on: ubuntu-latest 

    steps: 
      - name: checkout the repository 
        uses: actions/checkout@v4
      - name: setup the go 1.22 
        uses: actions/setup-go@v2
        with: 
          go-version: 1.22 
      - name: displaying the all files and folders in repository 
        run: ls 
      - name: checkout the test cases 
        run: 
          git clone https://github.com/mohantest14242/go_testing.git
      - name: displaying the all testcases along with the testcases 
        run: ls 
      